/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package restaurantorderingandpayment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Calendar;
import javax.swing.JTable;
import javax.swing.Timer;

public class Loading3 extends javax.swing.JDialog {

    public interface Observer {
        
        public void loadingDidComplete();
    }
    Timer timer = null;
     public Loading3.Observer observer1;

    public Loading3(java.awt.Frame parent, Observer observer) {
        super(parent, true);
       this.observer1 = observer;
        initComponents();
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        timer = new Timer(10000, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                 observer.loadingDidComplete();
                dispose();
                 
            }
        });
        timer.setRepeats(false);
        timer.stop();
        timer.restart();
              CancelOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelOrderMouseClicked(evt);
            }
});

    
}

   public void CancelOrderMouseClicked(java.awt.event.MouseEvent evt) {                                         
        CancelOrder.setForeground(new java.awt.Color(255, 255, 255));
           
     
       dispose();
       timer.stop();
   }

     
    
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new RoundedPanel(new java.awt.Dimension(45, 45), 0);
        PleaseFIll = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CancelOrder = new javax.swing.JLabel();
        NoButton = new RoundedPanel(new java.awt.Dimension(33, 33), 0);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(24, 25, 32));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PleaseFIll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PleaseFIll.setForeground(new java.awt.Color(255, 255, 255));
        PleaseFIll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PleaseFIll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantorderingandpayment/images/sushiparade.gif"))); // NOI18N
        MainPanel.add(PleaseFIll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 100));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantorderingandpayment/images/loading.gif"))); // NOI18N
        MainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 20));

        CancelOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelOrder.setForeground(new java.awt.Color(30, 31, 52));
        CancelOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelOrder.setText("Cancel");
        CancelOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelOrderMouseExited(evt);
            }
        });
        MainPanel.add(CancelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 70, 30));

        NoButton.setBackground(new java.awt.Color(13, 245, 227));

        javax.swing.GroupLayout NoButtonLayout = new javax.swing.GroupLayout(NoButton);
        NoButton.setLayout(NoButtonLayout);
        NoButtonLayout.setHorizontalGroup(
            NoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        NoButtonLayout.setVerticalGroup(
            NoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        MainPanel.add(NoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelOrderMouseEntered
        CancelOrder.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_CancelOrderMouseEntered

    private void CancelOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelOrderMouseExited
        CancelOrder.setForeground(new java.awt.Color(30, 31, 50));
    }//GEN-LAST:event_CancelOrderMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            
              
           
                   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel CancelOrder;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel NoButton;
    private javax.swing.JLabel PleaseFIll;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
