/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package restaurantorderingandpayment;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Timer;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;


/**
 *
 * @author Jerickson Mayor
 */
public class OTPDialog extends javax.swing.JDialog {
     private Point initialClick;
     private static String phoneno;
     private static String fullname;
     private int count = 61;
     private Timer timer;
     private static char [] otp;
     String formattedString;
    public OTPDialog(java.awt.Frame parent, boolean modal, String fullname, String phoneno, char[] otp) {
        super(parent, modal);
        this.phoneno = phoneno;
        this.fullname = fullname;
        System.out.println(otp);
        this.otp = otp;
        initComponents();
      formattedString = Arrays.toString(otp)
    .replace(",", "")  //remove the commas
    .replace("[", "")  //remove the right bracket
    .replace("]", "")  //remove the left bracket
    .replaceAll("\\s+", "") // remove all spaces
    .trim();
        invalid.setVisible(false);
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        userno.setText("+"+phoneno);
        setModal(true);
        
    ActionListener taskPerformer = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        //What should the timer do?
        
        count--;
        countdown.setText(Integer.toString(count));
        countdown.setText(Integer.toString(count));
        if (count == 0 && timer.isRunning()) {
            count = 61;
            timer.stop();
            resend.setEnabled(true);
            Exit.setEnabled(true);
        
              
    
             countdown.setText("");
            
        }
      }
    }; 
       timer = new Timer(1000, taskPerformer);
    resend.addMouseListener(new MouseAdapter() {
      public void mouseClicked(MouseEvent e) {   
        resend.setEnabled(false);
        Exit.setEnabled(false);
        Exit.setToolTipText("Exit is disabled");
       
//        MouseListener[] mouseListeners = Exit.getMouseListeners();
//    for (int i = 0; i < mouseListeners.length; i++) {
//        Exit.removeMouseListener(mouseListeners[i]);
//    }
       if (!timer.isRunning() && resend.isEnabled() == false) {
           SendSMS sms = new SendSMS();
//          try {
//              sms.sendSMS(phoneno, "Hello " +fullname+"," + " your OTP is :" +formattedString);
//          } catch (IOException ex) {
//              System.out.println(ex);
//              Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
//          }
           SMS2 sms2 = new SMS2();
           sms2.sendSMS(phoneno, "Hello " +fullname+"," + " your OTP is :" +formattedString);

           timer.start();
       }
}
        
      
    });
    ((AbstractDocument)otpfield.getDocument()).setDocumentFilter(new DocumentFilter(){
        Pattern regEx = Pattern.compile("\\d*");

        @Override
        public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {          
            Matcher matcher = regEx.matcher(text);
            if(!matcher.matches()){
                Toolkit.getDefaultToolkit().beep();
                return;
                
            }
            super.replace(fb, offset, length, text, attrs);
        }
    });
        System.out.println(formattedString);
    }   

    
     
       //          X x=new X();
//X.Y y=x.new Y();
       
        
      
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new RoundedPanel(new java.awt.Dimension(45, 45), 0);
        NoButton = new RoundedPanel(new java.awt.Dimension(45, 45), 0);
        verifyotp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        otpfield = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        userno = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        resend = new javax.swing.JLabel();
        countdown = new javax.swing.JLabel();
        invalid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(24, 25, 32));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoButton.setBackground(new java.awt.Color(13, 245, 227));

        verifyotp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        verifyotp.setForeground(new java.awt.Color(30, 31, 52));
        verifyotp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifyotp.setText("Verify OTP");
        verifyotp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verifyotp.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                verifyotpAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        verifyotp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verifyotpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verifyotpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verifyotpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout NoButtonLayout = new javax.swing.GroupLayout(NoButton);
        NoButton.setLayout(NoButtonLayout);
        NoButtonLayout.setHorizontalGroup(
            NoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(verifyotp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        NoButtonLayout.setVerticalGroup(
            NoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(verifyotp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(NoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantorderingandpayment/images/lock.png"))); // NOI18N
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 30, 30));

        TextPrompt otp = new TextPrompt("OTP PIN", otpfield);
        otp.setForeground(new java.awt.Color(107, 102, 117));
        otp.setFont(new java.awt.Font("Segoe UI", 1, 13));
        otpfield.setBackground(new java.awt.Color(24, 25, 32));
        otpfield.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        otpfield.setForeground(new java.awt.Color(255, 255, 255));
        otpfield.setBorder(null);
        otpfield.setCaretColor(new java.awt.Color(255, 255, 255));
        otpfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otpfieldKeyTyped(evt);
            }
        });
        MainPanel.add(otpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        MainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("We have sent verification to");
        MainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 260, -1));

        userno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userno.setForeground(new java.awt.Color(255, 255, 255));
        userno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(userno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 260, 20));

        Exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(104, 101, 112));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.setToolTipText("Exit");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        MainPanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 30, 20));

        resend.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        resend.setForeground(new java.awt.Color(255, 255, 255));
        resend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resend.setText("Resend SMS");
        resend.setToolTipText("Click to resend SMS");
        resend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resendMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resendMouseExited(evt);
            }
        });
        MainPanel.add(resend, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 60, 20));

        countdown.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        countdown.setForeground(new java.awt.Color(13, 245, 227));
        MainPanel.add(countdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 30, 20));

        invalid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        invalid.setForeground(new java.awt.Color(181, 45, 45));
        invalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invalid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantorderingandpayment/images/warningmessage.png"))); // NOI18N
        invalid.setText("Invalid OTP !");
        MainPanel.add(invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(260, 197));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void verifyotpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verifyotpMouseEntered
        verifyotp.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_verifyotpMouseEntered

    private void verifyotpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verifyotpMouseExited
        verifyotp.setForeground(new java.awt.Color(30, 31, 50));
    }//GEN-LAST:event_verifyotpMouseExited

    private void verifyotpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verifyotpMouseClicked
         String otptemp = otpfield.getText();
        
char[] verifyotp = otptemp.toCharArray();
        
      boolean verify = Arrays.equals(otp, verifyotp);
       
      
      if (verify) {
          this.dispose();
          LoginForm.isvalidated = true;
      

       
        
        
      }
      else {
          invalid.setVisible(true);
      }
         
    }//GEN-LAST:event_verifyotpMouseClicked

    private void otpfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otpfieldKeyTyped
        if (otpfield.getText().length() == 6) {
                     evt.consume();
                     Toolkit.getDefaultToolkit().beep();
                 }
         if (otpfield.getText().length() > 0) { 
                invalid.setVisible(false);
            }
    }//GEN-LAST:event_otpfieldKeyTyped

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        if (Exit.isEnabled()) {
             this.dispose();
        }
    
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit.setForeground(new java.awt.Color(255, 119, 119));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit.setForeground(new java.awt.Color(104,101,112));
    }//GEN-LAST:event_ExitMouseExited

    private void resendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resendMouseClicked
          
//        if (resend.isEnabled()) {
//            resend.setEnabled(false);
//        }
      
        
    }//GEN-LAST:event_resendMouseClicked

    private void resendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resendMouseEntered
      resend.setForeground(new java.awt.Color(13,245,227));
    }//GEN-LAST:event_resendMouseEntered

    private void resendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resendMouseExited
      resend.setForeground(new java.awt.Color(255, 255, 255)); 
    }//GEN-LAST:event_resendMouseExited

    private void verifyotpAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_verifyotpAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_verifyotpAncestorAdded


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OTPDialog dialog = new OTPDialog(new javax.swing.JFrame(), true, fullname, phoneno, otp);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel NoButton;
    private javax.swing.JLabel countdown;
    private javax.swing.JLabel invalid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField otpfield;
    private javax.swing.JLabel resend;
    private javax.swing.JLabel userno;
    private javax.swing.JLabel verifyotp;
    // End of variables declaration//GEN-END:variables
}
