package restaurantorderingandpayment;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.plaf.ColorUIResource;

public class SplashScreen extends javax.swing.JFrame {
   
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/restaurantorderingandpayment/images/flaticon2.png")));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new RoundedPanel(new java.awt.Dimension(45, 45) ,0);
        ProgressBar = new javax.swing.JProgressBar();
        SplashLogo = new javax.swing.JLabel();
        ProgressAnim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(31, 25, 46));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProgressBar.setBackground(new java.awt.Color(12, 12, 13));
        ProgressBar.setForeground(new java.awt.Color(13, 245, 227));
        ProgressBar.setBorder(null);
        ProgressBar.setOpaque(false);
        ProgressBar.setStringPainted(true);
        MainPanel.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, -1));

        SplashLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SplashLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantorderingandpayment/images/ridingdonut.gif"))); // NOI18N
        MainPanel.add(SplashLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 140));

        ProgressAnim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProgressAnim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantorderingandpayment/images/loading.gif"))); // NOI18N
        MainPanel.add(ProgressAnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    javax.swing.UIManager.getLookAndFeelDefaults().put("ProgressBar[Enabled].backgroundPainter", new FillPainter(new Color(12, 12, 13))); 
//javax.swing.UIManager.getLookAndFeelDefaults().put("ProgressBar[Disabled].backgroundPainter", new FillPainter(new Color(12, 12, 13))); 
//javax.swing.UIManager.getLookAndFeelDefaults().put("ProgressBar[Enabled+Indeterminate].progressPadding", new FillPainter(new Color(12, 12, 13))); 
//javax.swing.UIManager.getLookAndFeelDefaults().put("ProgressBar[Enabled].foregroundPainter", new FillPainter(new Color(23, 50, 255))); 
//javax.swing.UIManager.getLookAndFeelDefaults().put("ProgressBar[Disabled].foregroundPainter", new FillPainter(new Color(23, 50, 255))); 
//javax.swing.UIManager.getLookAndFeelDefaults().put("ProgressBar[Enabled+Finished].foregroundPainter", new FillPainter(new Color(23, 50, 255))); 
//javax.swing.UIManager.getLookAndFeelDefaults().put("ProgressBar[Disabled+Finished].foregroundPainter", new FillPainter(new Color(23, 50, 255))); 
//javax.swing.UIManager.getLookAndFeelDefaults().put("ProgressBar[Disabled+Indeterminate].foregroundPainter", new FillPainter(new Color(23, 50, 255))); 
//javax.swing.UIManager.getLookAndFeelDefaults().put("ProgressBar[Enabled+Indeterminate].foregroundPainter", new FillPainter(new Color(23, 50, 255))); 
ColorUIResource colorResource = new ColorUIResource(Color.red.darker().darker());
javax.swing.UIManager.put("nimbusOrange",colorResource);

                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
               
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel ProgressAnim;
    public static javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel SplashLogo;
    // End of variables declaration//GEN-END:variables
}
