/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package restaurantorderingandpayment;
import java.awt.Point;
import java.awt.event.WindowEvent;

/**
 *
 * @author Jerickson Mayor
 */
public class Success extends javax.swing.JDialog {
     private Point initialClick;
    /**
     * Creates new form ShowConfirmDIalog
     */
    public Success(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new RoundedPanel(new java.awt.Dimension(45, 45), 0);
        NoButton = new RoundedPanel(new java.awt.Dimension(45, 45), 0);
        No = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PleaseFIll = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(24, 25, 32));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoButton.setBackground(new java.awt.Color(13, 245, 227));

        No.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        No.setForeground(new java.awt.Color(30, 31, 52));
        No.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        No.setText("Okay");
        No.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout NoButtonLayout = new javax.swing.GroupLayout(NoButton);
        NoButton.setLayout(NoButtonLayout);
        NoButtonLayout.setHorizontalGroup(
            NoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        NoButtonLayout.setVerticalGroup(
            NoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(NoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantorderingandpayment/images/success.png"))); // NOI18N
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 40, 30));

        PleaseFIll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PleaseFIll.setForeground(new java.awt.Color(255, 255, 255));
        PleaseFIll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PleaseFIll.setText("Successfully Sign up");
        MainPanel.add(PleaseFIll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoMouseEntered
        No.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_NoMouseEntered

    private void NoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoMouseExited
        No.setForeground(new java.awt.Color(30, 31, 50));
    }//GEN-LAST:event_NoMouseExited

    private void NoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoMouseClicked
        
       this.dispose();
    }//GEN-LAST:event_NoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Success dialog = new Success(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel No;
    private javax.swing.JPanel NoButton;
    private javax.swing.JLabel PleaseFIll;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
